# Generated by Django 3.1 on 2022-04-24 15:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.CharField(choices=[('+', 'INCOME'), ('', 'OUTCOME')], default='+', max_length=5)),
                ('value', models.IntegerField()),
                ('desc', models.TextField()),
                ('time', models.DateTimeField(verbose_name=django.utils.timezone.now)),
            ],
        ),
    ]
