# Generated by Django 3.1 on 2022-04-24 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
