# Generated by Django 3.1 on 2022-04-25 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0002_auto_20220424_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='typ',
            field=models.CharField(choices=[('+', 'INCOME'), ('-', 'OUTCOME')], max_length=5),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inc_val', models.IntegerField()),
                ('out_val', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
